### ISSUE TITLE
[BUG] TFC salt water change texture when gregtech installed

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCE/GregTech#1561]
**Describe the bug**
TFC salt water change texture when gregtech installed

**Versions**
Forge: 2855
GTCE: gregtech-1.12.2-1.13.0.681.jar
_Modpack:_ TerraFirmaGreg, but i test with GregTech and TerraFirmaCraft only.

**Setup**
In all worlds, single or multi

**Steps To Reproduce**
1) Install Gregtech + TFC.
2) Enter the world

**Screenshots**
TerraFirmaCraft salt water with Gregtech:
https://user-images.githubusercontent.com/52341158/112114619-d9588f80-8bea-11eb-8118-431d5d9e2c55.png
TerraFirmaCraft salt water without Gregtech:
https://user-images.githubusercontent.com/52341158/112114899-2ccadd80-8beb-11eb-9a9c-aca3e4dbeebf.png

**Comment by DoctorWeirdGuy** [comment]
This happens if both fluids have the same fluid ID and since GTCE loads earlier than TFC, GTCE's fluid version gets used instead of TFC's salt water. Atleast that's what happens here I assume.

**Comment by Exzept1on** [comment]
Fixed in GTCEu

**Comment by Exaxxion** [comment]
You do realize that GTCEu is a completely separate project and not this one, right? The issue would still exist here.
