### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Timozer** [GregTechCE/GregTech#319]
Hi,
The game crashed when I use wrench to mine machines.

I am not sure which the problem belongs to(GPU Card or the mod)?

Here is the crash report.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  JechCore (JustEnoughCharacters-1.12.0-2.3.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 9/16/18 7:56 PM
Description: Tesselating block model

java.lang.ClassCastException: appeng.tile.misc.TileInscriber cannot be cast to gregtech.api.metatileentity.MetaTileEntityHolder
	at gregtech.api.block.machines.BlockMachine.getMetaTileEntity(BlockMachine.java:114)
	at gregtech.api.block.machines.BlockMachine.getLightValue(BlockMachine.java:358)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callInt(Reflector.java:847)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:514)
	at net.minecraft.block.Block.func_185484_c(Block.java:378)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:367)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_187491_a(BlockModelRenderer.java:614)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:187)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:125)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:89)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:76)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:55)
	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlockDamage(BlockRenderingRegistry.java:88)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175020_a(CCBlockRendererDispatcher.java:51)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2754)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1825)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregtech.api.block.machines.BlockMachine.getMetaTileEntity(BlockMachine.java:114)
	at gregtech.api.block.machines.BlockMachine.getLightValue(BlockMachine.java:358)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callInt(Reflector.java:847)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:514)
	at net.minecraft.block.Block.func_185484_c(Block.java:378)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:367)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_187491_a(BlockModelRenderer.java:614)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:187)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:125)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:89)

-- Block model being tesselated --
Details:
	Block: gregtech:machine[opaque=true]
	Block location: World: (211,63,227), Chunk: (at 3,3,3 in 13,14; contains blocks 208,0,224 to 223,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:76)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:55)
	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlockDamage(BlockRenderingRegistry.java:88)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175020_a(CCBlockRendererDispatcher.java:51)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2754)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1825)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Timozer'/13002, l='MpServer', x=213.51, y=63.00, z=227.17]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (236,64,232), Chunk: (at 12,4,8 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11121428 game time, 11873252 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 118 total; [EntityBat['蝙蝠'/13580, l='MpServer', x=238.54, y=41.06, z=275.65], EntityBabySkeleton['骷髅射手宝宝'/13325, l='MpServer', x=258.50, y=82.00, z=260.50], EntityZombie['僵尸'/13331, l='MpServer', x=143.50, y=64.00, z=181.50], EntityBabySkeleton['骷髅射手宝宝'/12312, l='MpServer', x=214.50, y=50.00, z=174.50], EntitySkeleton['骷髅'/3353, l='MpServer', x=228.45, y=43.00, z=216.22], EntityItem['item.item.egg'/13595, l='MpServer', x=203.11, y=68.00, z=188.87], EntityCreeper['爬行者'/13854, l='MpServer', x=213.50, y=16.00, z=210.50], EntityPig['猪'/31, l='MpServer', x=143.25, y=75.00, z=211.50], EntitySquid['鱿鱼'/13855, l='MpServer', x=212.60, y=50.94, z=290.86], EntityCreeper['爬行者'/7200, l='MpServer', x=214.30, y=41.00, z=217.25], EntityChicken['鸡'/33, l='MpServer', x=137.50, y=65.00, z=236.13], EntityCreeper['爬行者'/7201, l='MpServer', x=213.50, y=44.00, z=230.15], EntityCreeper['爬行者'/13089, l='MpServer', x=154.50, y=64.00, z=283.50], EntityCreeper['爬行者'/13601, l='MpServer', x=268.50, y=68.00, z=198.50], EntityEnderman['末影人'/7202, l='MpServer', x=220.34, y=42.00, z=209.53], EntityChicken['鸡'/35, l='MpServer', x=135.61, y=67.00, z=253.94], EntityEnderman['末影人'/7203, l='MpServer', x=219.38, y=41.00, z=212.51], EntityItem['item.item.egg'/9508, l='MpServer', x=231.50, y=91.00, z=231.83], EntityChicken['鸡'/37, l='MpServer', x=143.54, y=66.00, z=266.12], EntityChicken['鸡'/40, l='MpServer', x=138.11, y=64.00, z=272.25], EntitySquid['鱿鱼'/13867, l='MpServer', x=197.49, y=50.03, z=284.35], EntitySquid['鱿鱼'/13868, l='MpServer', x=195.65, y=50.01, z=285.79], EntitySquid['鱿鱼'/13869, l='MpServer', x=199.79, y=48.15, z=284.42], EntitySquid['鱿鱼'/13870, l='MpServer', x=193.29, y=47.90, z=281.89], EntitySquid['鱿鱼'/13871, l='MpServer', x=206.31, y=57.99, z=282.83], EntitySkeleton['骷髅'/13360, l='MpServer', x=199.50, y=52.00, z=151.50], EntitySquid['鱿鱼'/13872, l='MpServer', x=212.49, y=57.83, z=284.36], EntitySkeleton['骷髅'/13361, l='MpServer', x=266.50, y=13.00, z=254.50], EntitySquid['鱿鱼'/13873, l='MpServer', x=208.60, y=56.02, z=277.35], EntitySquid['鱿鱼'/13874, l='MpServer', x=213.60, y=56.12, z=280.39], EntityPig['猪'/51, l='MpServer', x=151.32, y=66.00, z=188.51], EntityChicken['鸡'/52, l='MpServer', x=139.20, y=73.00, z=204.80], EntityPig['猪'/53, l='MpServer', x=150.51, y=75.00, z=203.71], EntityChicken['鸡'/55, l='MpServer', x=145.28, y=67.00, z=259.87], EntitySquid['鱿鱼'/13879, l='MpServer', x=170.07, y=60.41, z=285.29], EntitySquid['鱿鱼'/13880, l='MpServer', x=170.16, y=60.53, z=281.92], EntitySquid['鱿鱼'/13881, l='MpServer', x=172.79, y=60.16, z=284.68], EntitySquid['鱿鱼'/13882, l='MpServer', x=173.98, y=60.89, z=286.57], EntityPigZombie['僵尸猪人'/13373, l='MpServer', x=235.50, y=68.00, z=232.50], EntityBat['蝙蝠'/13637, l='MpServer', x=188.48, y=52.32, z=171.23], EntityChicken['鸡'/71, l='MpServer', x=168.13, y=69.00, z=158.49], EntityPlayerSP['Timozer'/13002, l='MpServer', x=213.51, y=63.00, z=227.17], EntitySquid['鱿鱼'/13896, l='MpServer', x=190.01, y=51.91, z=281.75], EntitySquid['鱿鱼'/13897, l='MpServer', x=190.33, y=50.10, z=282.09], EntitySquid['鱿鱼'/13898, l='MpServer', x=192.34, y=49.94, z=280.98], EntitySquid['鱿鱼'/13899, l='MpServer', x=193.43, y=52.09, z=278.26], EntityBat['蝙蝠'/13397, l='MpServer', x=159.75, y=36.70, z=158.75], EntityBat['蝙蝠'/13146, l='MpServer', x=252.12, y=33.89, z=233.20], EntityBat['蝙蝠'/13147, l='MpServer', x=237.64, y=21.00, z=222.75], EntityBat['蝙蝠'/13148, l='MpServer', x=249.52, y=34.20, z=235.00], EntityBat['蝙蝠'/13664, l='MpServer', x=243.56, y=24.76, z=218.51], EntityChicken['鸡'/102, l='MpServer', x=203.51, y=68.00, z=188.18], EntityChicken['鸡'/106, l='MpServer', x=223.50, y=69.00, z=149.90], EntityCreeper['爬行者'/112, l='MpServer', x=217.40, y=41.00, z=217.84], EntityEnderman['末影人'/113, l='MpServer', x=213.73, y=42.00, z=212.50], EntityZombie['僵尸'/114, l='MpServer', x=211.55, y=42.00, z=224.76], EntityCreeper['爬行者'/115, l='MpServer', x=219.53, y=42.00, z=220.15], EntitySkeleton['骷髅'/116, l='MpServer', x=214.54, y=38.00, z=212.21], EntitySkeleton['骷髅'/117, l='MpServer', x=216.13, y=42.00, z=215.86], EntitySkeleton['骷髅'/118, l='MpServer', x=213.51, y=42.00, z=226.29], EntitySkeleton['骷髅'/119, l='MpServer', x=214.79, y=41.00, z=216.51], EntitySkeleton['骷髅'/7035, l='MpServer', x=222.68, y=41.00, z=208.55], EntitySkeleton['骷髅'/7036, l='MpServer', x=215.66, y=44.00, z=231.51], EntityCreeper['爬行者'/138, l='MpServer', x=229.50, y=43.00, z=218.50], EntityBat['蝙蝠'/139, l='MpServer', x=226.56, y=47.10, z=208.06], EntityZombie['僵尸'/13707, l='MpServer', x=188.50, y=63.00, z=259.50], EntityZombie['僵尸'/13708, l='MpServer', x=188.50, y=63.00, z=257.50], EntityChicken['鸡'/141, l='MpServer', x=231.96, y=91.00, z=231.23], EntityZombie['僵尸'/13453, l='MpServer', x=172.50, y=48.00, z=186.50], EntityChicken['鸡'/142, l='MpServer', x=232.15, y=91.00, z=231.68], EntityBabySkeleton['骷髅射手宝宝'/13454, l='MpServer', x=173.50, y=48.00, z=186.50], EntityZombie['僵尸'/13710, l='MpServer', x=178.33, y=72.00, z=208.75], EntitySheep['羊'/143, l='MpServer', x=229.12, y=91.00, z=231.84], EntitySheep['羊'/144, l='MpServer', x=228.80, y=91.00, z=228.20], EntityZombie['僵尸'/13712, l='MpServer', x=170.50, y=73.00, z=219.50], EntitySheep['羊'/145, l='MpServer', x=228.79, y=91.00, z=227.01], EntityChicken['鸡'/146, l='MpServer', x=231.46, y=91.00, z=230.79], EntitySheep['羊'/147, l='MpServer', x=229.92, y=91.00, z=232.78], EntityChicken['鸡'/148, l='MpServer', x=232.44, y=91.00, z=227.79], EntityChicken['鸡'/149, l='MpServer', x=231.45, y=91.00, z=231.61], EntityItem['item.item.egg'/13461, l='MpServer', x=231.79, y=91.00, z=227.39], EntityChicken['鸡'/150, l='MpServer', x=232.87, y=91.00, z=231.60], EntitySheep['羊'/151, l='MpServer', x=229.92, y=91.00, z=228.15], EntitySheep['羊'/152, l='MpServer', x=229.92, y=91.00, z=227.01], EntitySheep['羊'/153, l='MpServer', x=227.73, y=91.00, z=227.01], EntityBat['蝙蝠'/13731, l='MpServer', x=234.87, y=14.12, z=172.86], EntityBat['蝙蝠'/13479, l='MpServer', x=135.88, y=21.27, z=194.25], EntityPig['猪'/174, l='MpServer', x=271.70, y=86.00, z=284.51], EntityZombie['僵尸'/12978, l='MpServer', x=267.22, y=56.00, z=226.50], EntityChicken['鸡'/178, l='MpServer', x=273.60, y=86.00, z=153.50], EntityChicken['鸡'/179, l='MpServer', x=277.51, y=82.00, z=153.57], EntityChicken['鸡'/183, l='MpServer', x=284.70, y=73.00, z=161.11], EntityChicken['鸡'/184, l='MpServer', x=275.83, y=76.00, z=179.52], EntityPig['猪'/185, l='MpServer', x=282.65, y=73.00, z=182.39], EntitySkeleton['骷髅'/7868, l='MpServer', x=210.30, y=68.00, z=208.61], EntityChicken['鸡'/189, l='MpServer', x=287.80, y=83.00, z=240.51], EntityPig['猪'/190, l='MpServer', x=287.70, y=88.00, z=248.58], EntityPig['猪'/194, l='MpServer', x=286.07, y=87.00, z=279.34], EntityBat['蝙蝠'/13762, l='MpServer', x=153.52, y=19.00, z=179.25], EntityBat['蝙蝠'/13763, l='MpServer', x=148.53, y=18.84, z=180.55], EntitySkeleton['骷髅'/4806, l='MpServer', x=232.47, y=44.00, z=225.25], EntityPig['猪'/212, l='MpServer', x=290.50, y=89.00, z=302.75], EntitySkeleton['骷髅'/13781, l='MpServer', x=291.50, y=68.00, z=254.50], EntitySkeleton['骷髅'/13783, l='MpServer', x=229.50, y=70.00, z=160.50], EntityBat['蝙蝠'/13528, l='MpServer', x=154.82, y=22.67, z=204.45], EntitySkeleton['骷髅'/13786, l='MpServer', x=231.50, y=70.00, z=161.50], EntityZombieVillager['僵尸村民'/4843, l='MpServer', x=225.79, y=39.00, z=213.57], EntityZombieVillager['僵尸村民'/4844, l='MpServer', x=211.51, y=43.00, z=227.80], EntityZombie['僵尸'/4079, l='MpServer', x=221.05, y=42.00, z=216.08], EntityItem['item.item.egg'/11248, l='MpServer', x=232.79, y=91.00, z=227.40], EntitySpider['蜘蛛'/13300, l='MpServer', x=272.50, y=66.00, z=212.50], EntityBat['蝙蝠'/13812, l='MpServer', x=276.85, y=15.02, z=223.84], EntityBabySkeleton['骷髅射手宝宝'/13301, l='MpServer', x=270.47, y=68.00, z=197.48], EntityZombie['僵尸'/13557, l='MpServer', x=179.73, y=70.00, z=228.42], EntityBabySkeleton['骷髅射手宝宝'/13302, l='MpServer', x=270.50, y=66.00, z=207.50], EntityItem['item.item.egg'/13303, l='MpServer', x=233.25, y=91.00, z=231.36], EntitySpider['蜘蛛'/13559, l='MpServer', x=179.00, y=72.00, z=217.94], EntityBat['蝙蝠'/13819, l='MpServer', x=280.25, y=17.10, z=222.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 875424024 bytes (834 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 Optifine OptiFine_1.12.2_HD_U_C8 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                        | Signature                                |
	|:------ |:--------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                   | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.4.2758.jar                 | None                                     |
	| UCHIJA | forge                 | 14.23.4.2758             | forge-1.12.2-14.23.4.2758.jar                 | None                                     |
	| UCHIJA | jecharacters          | 1.12.0-2.3.2             | JustEnoughCharacters-1.12.0-2.3.2.jar         | None                                     |
	| UCHIJA | opencomputers|core    | 1.7.2.67                 | minecraft.jar                                 | None                                     |
	| UCHIJA | appliedenergistics2   | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar         | None                                     |
	| UCHIJA | buildcraftlib         | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcraftcore        | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcraftbuilders    | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcraftenergy      | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcraftfactory     | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcraftrobotics    | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcrafttransport   | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | buildcraftsilicon     | 7.99.18                  | buildcraft-7.99.18.jar                        | None                                     |
	| UCHIJA | cd4017be_lib          | 6.2.4                    | CD4017BE_lib-1.12.2-6.2.4.jar                 | None                                     |
	| UCHIJA | codechickenlib        | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | crafttweaker          | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCHIJA | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCHIJA | jei                   | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                     | None                                     |
	| UCHIJA | crafttweakerjei       | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCHIJA | forgemultipartcbe     | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | microblockcbe         | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | None                                     |
	| UCHIJA | minecraftmultipartcbe | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | None                                     |
	| UCHIJA | gokistats             | @version@                | gokiStats-1.2.3.1.jar                         | None                                     |
	| UCHIJA | gregtech              | 0.5.8.79                 | gregtech-1.12.2-0.5.8.79.jar                  | None                                     |
	| UCHIJA | infinitylib           | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                        | None                                     |
	| UCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | journeymap            | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJA | jeresources           | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar       | None                                     |
	| UCHIJA | mantle                | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UCHIJA | mekanism              | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                | None                                     |
	| UCHIJA | mekanismgenerators    | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar      | None                                     |
	| UCHIJA | mekanismtools         | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar           | None                                     |
	| UCHIJA | metalchests           | v3.1.6.g7177eac          | MetalChests-v3.1.6.g7177eac.jar               | None                                     |
	| UCHIJA | mousetweaks           | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| UCHIJA | nei                   | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.238-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | opencomputers         | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar           | None                                     |
	| UCHIJA | tconstruct            | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar               | None                                     |
	| UCHIJA | theoneprobe           | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                   | None                                     |
	| UCHIJA | trackapi              | 1.1                      | TrackAPI-1.1_1.12.jar                         | None                                     |
	| UCHIJA | wanionlib             | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                      | None                                     |
	| UCHIJA | unidict               | 1.12.2-2.7b              | UniDict-1.12.2-2.7b.jar                       | None                                     |

	Loaded coremods (and transformers): 
JechCore (JustEnoughCharacters-1.12.0-2.3.2.jar)
  me.towdium.jecharacters.core.JechClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.59' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Launched Version: HMCL 2.5.0.65
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC112.zip, BDcraft Musics MC111.zip, BDcraft Sounds MC111.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.59
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by Exidex** [comment]
It was fixed in latest builds

**Comment by Timozer** [comment]
The latest version is 0.5.8.79 on curseforge. The version I use is 0.5.8.79 too. The game still crashed.

**Comment by Exidex** [comment]
it is not on curseforge yet. Dev builds are here https://gitlab.com/GregTechCE/GregTech/pipelines

**Comment by Timozer** [comment]
Ok, thanks! :+1:
